// This file is generated by Sapper — do not edit it!
import root from "../routes/_layout.html";
import error from "../routes/_error.html";

const d = decodeURIComponent;

const index = {
	js: () => import(/* webpackChunkName: "index" */ "../routes/index.html"),
	css: "__SAPPER_CSS_PLACEHOLDER:index.html__"
};
const contact$45us = {
	js: () => import(/* webpackChunkName: "contact$45us" */ "../routes/contact-us.html"),
	css: "__SAPPER_CSS_PLACEHOLDER:contact-us.html__"
};
const locations = {
	js: () => import(/* webpackChunkName: "locations" */ "../routes/locations/index.html"),
	css: "__SAPPER_CSS_PLACEHOLDER:locations/index.html__"
};
const locations_$slug = {
	js: () => import(/* webpackChunkName: "locations_$slug" */ "../routes/locations/[slug].html"),
	css: "__SAPPER_CSS_PLACEHOLDER:locations/[slug].html__"
};
const our$45story = {
	js: () => import(/* webpackChunkName: "our$45story" */ "../routes/our-story.html"),
	css: "__SAPPER_CSS_PLACEHOLDER:our-story.html__"
};
const products = {
	js: () => import(/* webpackChunkName: "products" */ "../routes/products.html"),
	css: "__SAPPER_CSS_PLACEHOLDER:products.html__"
};
const gallery = {
	js: () => import(/* webpackChunkName: "gallery" */ "../routes/gallery/index.html"),
	css: "__SAPPER_CSS_PLACEHOLDER:gallery/index.html__"
};
const gallery_share = {
	js: () => import(/* webpackChunkName: "gallery_share" */ "../routes/gallery/share.html"),
	css: "__SAPPER_CSS_PLACEHOLDER:gallery/share.html__"
};
const events = {
	js: () => import(/* webpackChunkName: "events" */ "../routes/events/index.html"),
	css: "__SAPPER_CSS_PLACEHOLDER:events/index.html__"
};
const events_$slug = {
	js: () => import(/* webpackChunkName: "events_$slug" */ "../routes/events/[slug].html"),
	css: "__SAPPER_CSS_PLACEHOLDER:events/[slug].html__"
};

export const manifest = {
	ignore: [/^\/locations.json$/, /^\/locations\/([^\/]+?).json$/, /^\/events.json$/, /^\/events\/([^\/]+?).json$/],

	pages: [
		{
			// index.html
			pattern: /^\/?$/,
			parts: [
				{ component: index }
			]
		},

		{
			// contact-us.html
			pattern: /^\/contact-us\/?$/,
			parts: [
				{ component: contact$45us }
			]
		},

		{
			// locations/index.html
			pattern: /^\/locations\/?$/,
			parts: [
				null,
				{ component: locations }
			]
		},

		{
			// locations/[slug].html
			pattern: /^\/locations\/([^\/]+?)\/?$/,
			parts: [
				null,
				{ component: locations_$slug, params: match => ({ slug: d(match[1]) }) }
			]
		},

		{
			// our-story.html
			pattern: /^\/our-story\/?$/,
			parts: [
				{ component: our$45story }
			]
		},

		{
			// products.html
			pattern: /^\/products\/?$/,
			parts: [
				{ component: products }
			]
		},

		{
			// gallery/index.html
			pattern: /^\/gallery\/?$/,
			parts: [
				null,
				{ component: gallery }
			]
		},

		{
			// gallery/share.html
			pattern: /^\/gallery\/share\/?$/,
			parts: [
				null,
				{ component: gallery_share }
			]
		},

		{
			// events/index.html
			pattern: /^\/events\/?$/,
			parts: [
				null,
				{ component: events }
			]
		},

		{
			// events/[slug].html
			pattern: /^\/events\/([^\/]+?)\/?$/,
			parts: [
				null,
				{ component: events_$slug, params: match => ({ slug: d(match[1]) }) }
			]
		}
	],

	root,

	error
};

// this is included for legacy reasons
export const routes = {};

import("/home/danielsokil/Desktop/Projects/European-Market/web-application/client/node_modules/sapper/sapper-dev-client.js").then(client => {
	client.connect(10000);
});