// This file is generated by Sapper — do not edit it!
export const timestamp = 1546849107156;

export const files = [
	"css/global.css",
	"css/modern-normalize.css",
	"css/normalize.css",
	"favicon.png",
	"images/european-meats-min.jpg",
	"images/european-meats.jpg",
	"images/fresh-vegetables-min.jpg",
	"images/fresh-vegetables.jpg",
	"images/homemade-blintzes-min.jpg",
	"images/homemade-blintzes.jpg",
	"images/homemade-cabbage-rolls-min.jpg",
	"images/homemade-cabbage-rolls.jpg",
	"images/homemade-pelmeni-min.jpg",
	"images/homemade-pelmeni.jpg",
	"images/homemade-perogies-min.jpg",
	"images/homemade-perogies.jpg",
	"images/polish-meats-min.jpg",
	"images/polish-meats.jpg",
	"images/social/facebook.png",
	"images/social/instagram.png",
	"images/social/pinterest.png",
	"images/social/twitter.png",
	"lib/tiny-slider-2.8.8/tiny-slider.css",
	"lib/tiny-slider-2.8.8/tiny-slider.helper.ie8.js",
	"lib/tiny-slider-2.8.8/tiny-slider.js",
	"lib/typeboost.css-0.1.8/typeboost.css",
	"lib/typeboost.css-0.1.8/typeboost.min.css",
	"manifest.json",
	"svelte-logo-192.png",
	"svelte-logo-512.png"
];
export { files as assets }; // legacy

export const shell = [
	"client/1c8db248180dbfd7b03a/0.0.js",
	"client/1c8db248180dbfd7b03a/contact$45us.contact$45us.js",
	"client/1c8db248180dbfd7b03a/events.events.js",
	"client/1c8db248180dbfd7b03a/events_$slug.events_$slug.js",
	"client/1c8db248180dbfd7b03a/gallery.gallery.js",
	"client/1c8db248180dbfd7b03a/gallery_share.gallery_share.js",
	"client/1c8db248180dbfd7b03a/index.index.js",
	"client/1c8db248180dbfd7b03a/locations.locations.js",
	"client/1c8db248180dbfd7b03a/locations_$slug.locations_$slug.js",
	"client/1c8db248180dbfd7b03a/main.js",
	"client/1c8db248180dbfd7b03a/our$45story.our$45story.js",
	"client/1c8db248180dbfd7b03a/products.products.js",
	"client/1c8db248180dbfd7b03a/vendors~gallery.vendors~gallery.js"
];

export const routes = [
	{ pattern: /^\/?$/ },
	{ pattern: /^\/contact-us\/?$/ },
	{ pattern: /^\/locations\/?$/ },
	{ pattern: /^\/locations\/([^\/]+?)\/?$/ },
	{ pattern: /^\/our-story\/?$/ },
	{ pattern: /^\/products\/?$/ },
	{ pattern: /^\/gallery\/?$/ },
	{ pattern: /^\/gallery\/share\/?$/ },
	{ pattern: /^\/events\/?$/ },
	{ pattern: /^\/events\/([^\/]+?)\/?$/ }
];