// This file is generated by Sapper — do not edit it!
import * as route_locations_json from "../routes/locations/index.json.js";
import * as route_locations_$slug_json from "../routes/locations/[slug].json.js";
import * as route_events_json from "../routes/events/index.json.js";
import * as route_events_$slug_json from "../routes/events/[slug].json.js";
import index from "../routes/index.html";
import contact$45us from "../routes/contact-us.html";
import locations from "../routes/locations/index.html";
import locations_$slug from "../routes/locations/[slug].html";
import our$45story from "../routes/our-story.html";
import products from "../routes/products.html";
import gallery from "../routes/gallery/index.html";
import gallery_share from "../routes/gallery/share.html";
import events from "../routes/events/index.html";
import events_$slug from "../routes/events/[slug].html";
import root from "../routes/_layout.html";
import error from "../routes/_error.html";

const d = decodeURIComponent;

export const manifest = {
	server_routes: [
		{
			// locations/index.json.js
			pattern: /^\/locations.json$/,
			handlers: route_locations_json,
			params: () => ({})
		},

		{
			// locations/[slug].json.js
			pattern: /^\/locations\/([^\/]+?).json$/,
			handlers: route_locations_$slug_json,
			params: match => ({ slug: d(match[1]) })
		},

		{
			// events/index.json.js
			pattern: /^\/events.json$/,
			handlers: route_events_json,
			params: () => ({})
		},

		{
			// events/[slug].json.js
			pattern: /^\/events\/([^\/]+?).json$/,
			handlers: route_events_$slug_json,
			params: match => ({ slug: d(match[1]) })
		}
	],

	pages: [
		{
			// index.html
			pattern: /^\/?$/,
			parts: [
				{ name: "index", file: "index.html", component: index }
			]
		},

		{
			// contact-us.html
			pattern: /^\/contact-us\/?$/,
			parts: [
				{ name: "contact$45us", file: "contact-us.html", component: contact$45us }
			]
		},

		{
			// locations/index.html
			pattern: /^\/locations\/?$/,
			parts: [
				null,
				{ name: "locations", file: "locations/index.html", component: locations }
			]
		},

		{
			// locations/[slug].html
			pattern: /^\/locations\/([^\/]+?)\/?$/,
			parts: [
				null,
				{ name: "locations_$slug", file: "locations/[slug].html", component: locations_$slug, params: match => ({ slug: d(match[1]) }) }
			]
		},

		{
			// our-story.html
			pattern: /^\/our-story\/?$/,
			parts: [
				{ name: "our$45story", file: "our-story.html", component: our$45story }
			]
		},

		{
			// products.html
			pattern: /^\/products\/?$/,
			parts: [
				{ name: "products", file: "products.html", component: products }
			]
		},

		{
			// gallery/index.html
			pattern: /^\/gallery\/?$/,
			parts: [
				null,
				{ name: "gallery", file: "gallery/index.html", component: gallery }
			]
		},

		{
			// gallery/share.html
			pattern: /^\/gallery\/share\/?$/,
			parts: [
				null,
				{ name: "gallery_share", file: "gallery/share.html", component: gallery_share }
			]
		},

		{
			// events/index.html
			pattern: /^\/events\/?$/,
			parts: [
				null,
				{ name: "events", file: "events/index.html", component: events }
			]
		},

		{
			// events/[slug].html
			pattern: /^\/events\/([^\/]+?)\/?$/,
			parts: [
				null,
				{ name: "events_$slug", file: "events/[slug].html", component: events_$slug, params: match => ({ slug: d(match[1]) }) }
			]
		}
	],

	root,

	error
};

// this is included for legacy reasons
export const routes = {};